### ISSUE TITLE
go install bug

### ISSUE THREAD

**Issue by adaaaaaa** [gpustack/gguf-parser-go#1]
go: github.com/gpustack/gguf-parser-go/cmd/gguf-parser@latest (in github.com/gpustack/gguf-parser-go/cmd/gguf-parser@v0.0.0-20240830110418-95b2217e772a):
The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

**Comment by thxCode** [comment]
you can download it from the release page. `go install` does not support replacing the local module, we will remove this installation method from README later. thanks.

**Comment by kindy** [comment]
on macOS, download from release page and run will show some security warnings. below script works with go install:

**Note**: this script will do **rm -rf ./gguf-parser-go**

```
bash <<EOF

set -e # exit on fail
set -x # show cmd

rm -rf gguf-parser-go && mkdir -p gguf-parser-go
curl -L https://github.com/gpustack/gguf-parser-go/archive/refs/tags/v0.13.16.tar.gz | \
  tar --strip-components 1 -C gguf-parser-go -zxf -

cd gguf-parser-go/cmd/gguf-parser
CGO_ENABLED=1 go install -trimpath -ldflags="-w -s -X main.Version=local" \
  -tags="urfave_cli_no_docs netgo"

EOF

```

> works on macOS 15.3.1
